version: '3.8'

services:
  web:
    container_name: web_container
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
      - mysql
    networks:
      - lamp-network
  php:
    container_name: php_container
    image: php:8.2-fpm 
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - lamp-network

  mysql:
    container_name: mysql_container
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Luis28052005 
      MYSQL_DATABASE: mi_base_datos
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamp-network

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin:latest
    restart: always
    ports:
      - "81:80"
    environment:
      PMA_HOST: mysql  
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Luis28052005
    depends_on:
      - mysql
    networks:
      - lamp-network
networks:
  lamp-network:
    driver: bridge

volumes:
  db_data:
